# Generated by Django 6.0.7 on 2026-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('manager', 'مدیرعامل و کارشناس رسمی مسکن'), ('investment', 'مشاور سرمایه\u200cگذاری ملکی'), ('rent', 'مشاور برتر اجاره'), ('sale', 'مشاور برتر فروش'), ('legal', 'متخصص حقوقی و اتاق مذاکره')], max_length=20, verbose_name='سمت')),
                ('bio', models.TextField(verbose_name='بیوگرافی تخصصی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='عکس')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'name'],
            },
        ),
    ]
