# Generated by Django 6.0.7 on 2026-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ملک')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('transaction_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=4, verbose_name='نوع معامله')),
                ('area', models.PositiveIntegerField(verbose_name='متراژ (متر مربع)')),
                ('rooms', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد اتاق')),
                ('address', models.TextField(default='فاطمی، خ جویبار، سر بن\u200cبست بهمن', verbose_name='آدرس')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='تصویر شاخص')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'ملک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
