# Generated by Django 6.0.7 on 2026-07-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember', verbose_name='مشاور ملک'),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ودیعه (تومان)'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='بالکن'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='آسانسور'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_warehouse',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصویر ۲'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصویر ۳'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصویر ۴'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه باشد؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='اجاره ماهیانه (تومان)'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل طبقات'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['transaction_type'], name='properties__transac_682f08_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published'], name='properties__is_publ_b4a635_idx'),
        ),
    ]
